CREATE SCHEMA IF NOT EXISTS intelligence;
CREATE TABLE intelligence.selected (merchant_id text NOT NULL,request_key text NOT NULL,judgment jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(merchant_id,request_key));
CREATE TABLE intelligence.attempts (id text PRIMARY KEY,merchant_id text NOT NULL,request_key text NOT NULL,started_at timestamptz NOT NULL,reserved_cost numeric NOT NULL);
CREATE TABLE intelligence.attempt_results (attempt_id text PRIMARY KEY REFERENCES intelligence.attempts(id) ON DELETE CASCADE,merchant_id text NOT NULL,result jsonb NOT NULL);
CREATE TABLE intelligence.budgets (budget_key text NOT NULL,day date NOT NULL,spent numeric NOT NULL,PRIMARY KEY(budget_key,day));
ALTER TABLE intelligence.selected ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence.selected FORCE ROW LEVEL SECURITY;
CREATE POLICY selected_tenant ON intelligence.selected USING(merchant_id=current_setting('app.current_merchant_id',true)) WITH CHECK(merchant_id=current_setting('app.current_merchant_id',true));
ALTER TABLE intelligence.attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence.attempts FORCE ROW LEVEL SECURITY;
CREATE POLICY attempts_tenant ON intelligence.attempts USING(merchant_id=current_setting('app.current_merchant_id',true)) WITH CHECK(merchant_id=current_setting('app.current_merchant_id',true));
ALTER TABLE intelligence.attempt_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence.attempt_results FORCE ROW LEVEL SECURITY;
CREATE POLICY results_tenant ON intelligence.attempt_results USING(merchant_id=current_setting('app.current_merchant_id',true)) WITH CHECK(merchant_id=current_setting('app.current_merchant_id',true));
CREATE TABLE intelligence.repairs (merchant_id text NOT NULL,document_id text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(merchant_id,document_id));
ALTER TABLE intelligence.repairs ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence.repairs FORCE ROW LEVEL SECURITY;
CREATE POLICY repairs_tenant ON intelligence.repairs USING(merchant_id=current_setting('app.current_merchant_id',true)) WITH CHECK(merchant_id=current_setting('app.current_merchant_id',true));
CREATE TABLE intelligence.judgments (id text PRIMARY KEY,merchant_id text NOT NULL,request_key text NOT NULL,record jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE intelligence.judgments ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence.judgments FORCE ROW LEVEL SECURITY;
CREATE POLICY judgments_tenant ON intelligence.judgments USING(merchant_id=current_setting('app.current_merchant_id',true)) WITH CHECK(merchant_id=current_setting('app.current_merchant_id',true));
CREATE TABLE intelligence.raw_outputs (attempt_id text PRIMARY KEY REFERENCES intelligence.attempts(id) ON DELETE CASCADE,merchant_id text NOT NULL,body text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE intelligence.raw_outputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence.raw_outputs FORCE ROW LEVEL SECURITY;
CREATE POLICY raw_outputs_tenant ON intelligence.raw_outputs USING(merchant_id=current_setting('app.current_merchant_id',true)) WITH CHECK(merchant_id=current_setting('app.current_merchant_id',true));
